### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by bunt4021** [yarrm80s/orpheusdl-soundcloud#6]
Error when downloading https://soundcloud.com/yuli-chin/nct-127-kick-it-instrumental

```
Traceback (most recent call last):
  File "/orpheusdl/orpheus.py", line 224, in <module>
    main()
  File "/orpheusdl/orpheus.py", line 219, in main
    orpheus_core_download(orpheus, media_to_download, tpm, sdm, path)
  File "/orpheusdl/orpheus/core.py", line 401, in orpheus_core_download
    downloader.download_track(media_id, extra_kwargs=media.extra_kwargs)
  File "/orpheusdl/orpheus/music_downloader.py", line 294, in download_track
    track_info: TrackInfo = self.service.get_track_info(track_id, quality_tier, codec_options, **extra_kwargs)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/orpheusdl/modules/soundcloud/interface.py", line 138, in get_track_info
    genres = track_data['genre'].split('/') if 'genre' in track_data else None,
             ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split
```

**Comment by retinoic** [comment]
@bunt4021 you can wrap _track_data['genre']_ on line 138 in interface.py as a string to resolve this:

e.g. 

change
``genres = track_data['genre'].split('/') if 'genre' in track_data else None,``
to
``genres = str(track_data['genre']).split('/') if 'genre' in track_data else None,``

**Comment by OrfiDev** [comment]
@retinoic wouldn't that just make the genre say None or something instead? imo not a good solution, a better solution would be to replace if 'genre' in track_data with if track_data.get('genre')

**Comment by OrfiDev** [comment]
@retinoic a better solution would be to replace if 'genre' in track_data with if track_data.get('genre')

**Comment by retinoic** [comment]
@OrfiDev no, as it's not changing the logic, just ensuring the empty genre value is handled as a string so the .split() method is always successful (which is what threw the exception posted - attempting a string operation on an undefined null object). 

The key isn't missing, just a null value (e.g. track_data.get('genre') == true, but the value is null), so forcing track_data['genre'] to be a string will fix the exception reported in this Issue. 

In the current code's logic _None_ sets the tag to null if it's missing entirely, not a "None" string/tag.  Regardless of formatting (_if track_data.get('genre')_ vs _if 'genre' in track_data_), without reviewing the rest of the script, I assume it should still be assigned the null value (_else None_) if the key itself is missing entirely, but maybe not needed.

**Comment by retinoic** [comment]
@OrfiDev you're right, sorry - that's a better way to handle it.   The change should probably also be made to line 137 for release_date to avoid a similar exception with that tag if missing.

**Comment by login0false** [comment]
I am getting this error on Windows 10. From my inexperienced debugging, it appears that tracks without a stated genre report `'genre': None,` in TrackData, which evaluates to True by `if 'genre' in track_data`. I have replaced it with `if track_data.get("genre")` like it's done for release_date and it seems to work fine now.
